Add toolchain file (#2)
Resolves #1 (Add toolchain file).

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -54,19 +54,24 @@ function display_help_text()
     echo "        - Filenames are portable"
     echo "        - No whitespace errors are present"
     echo "        - No script errors are present"
+    echo "        - No build errors are present"
     echo "SYNOPSIS"
     echo "    $mnemonic --help"
     echo "    $mnemonic --version"
-    echo "    $mnemonic"
+    echo "    $mnemonic [--jobs <jobs>]"
     echo "OPTIONS"
     echo "    --help"
     echo "        Display this help text."
+    echo "    --jobs <jobs>"
+    echo "        Specify the number of build jobs to use when building. If the number of"
+    echo "        jobs is not specified, 'nproc - 1' jobs will be used."
     echo "    --version"
     echo "        Display the version of this script."
     echo "EXAMPLES"
     echo "    $mnemonic --help"
     echo "    $mnemonic --version"
     echo "    $mnemonic"
+    echo "    $mnemonic --jobs 1"
 }
 
 function display_version()
@@ -117,6 +122,40 @@ function ensure_no_script_errors_are_present()
     echo "none"
 }
 
+function ensure_no_build_errors_are_present()
+{
+    message "checking for build errors ......................... "
+
+    local -r toolchain_file="$repository/toolchain.cmake"
+    local -r build_directory="$repository/build"
+
+    if [[ ! -d "$build_directory" ]]; then
+        if ! cmake -DCMAKE_TOOLCHAIN_FILE="$toolchain_file" -S "$repository" -B "$build_directory" > "/dev/null" 2>&1; then
+            errors_found
+            error "aborting commit due to build CMake initialization error(s), listed below"
+            rm -rf "$build_directory"
+            cmake -DCMAKE_TOOLCHAIN_FILE="$toolchain_file" -S "$repository" -B "$build_directory"
+            abort
+        fi
+    fi
+
+    if ! cmake "$build_directory" > "/dev/null" 2>&1; then
+        errors_found
+        error "aborting commit due to build CMake configuration error(s), listed below"
+        cmake "$build_directory"
+        abort
+    fi
+
+    if ! cmake --build "$build_directory" -j "$build_jobs" > "/dev/null" 2>&1; then
+        errors_found
+        error "aborting commit due to build CMake build error(s), listed below"
+        cmake --build "$build_directory" -j "$build_jobs"
+        abort
+    fi
+
+    echo "none"
+}
+
 function main()
 {
     local -r script=$( readlink -f "$0" )
@@ -132,6 +171,17 @@ function main()
             --help)
                 display_help_text
                 exit
+                ;;
+            --jobs)
+                if [[ -n "$build_jobs" ]]; then
+                    abort "build job count already specified"
+                fi
+
+                if [[ "$#" -le 0 ]]; then
+                    abort "build job count not specified"
+                fi
+
+                local -r build_jobs="$1"; shift
                 ;;
             --version)
                 display_version
@@ -154,9 +204,14 @@ function main()
         local -r against=$( git hash-object -t tree "/dev/null" )
     fi
 
+    if [[ -z "$build_jobs" ]]; then
+        local -r build_jobs=$(( $( nproc ) - 1 ))
+    fi
+
     ensure_filenames_are_portable
     ensure_no_whitespace_errors_are_present
     ensure_no_script_errors_are_present
+    ensure_no_build_errors_are_present
 }
 
 main "$@"
